### ISSUE TITLE
Lua(https://www.lua.org/pil/25.html) / EcmaScript(https://duktape.org/) / Forth?

### ISSUE THREAD

**Issue by wipedlifepotato** [wipedlifepotato/bacteria#2]

**Comment by asmexcaliburwoods** [comment]
umbrella

**Comment by asmexcaliburwoods** [comment]
metascript

**Comment by asmexcaliburwoods** [comment]
во, github.com/ScriptableWorlds github.com/scriptableworld coop

**Comment by asmexcaliburwoods** [comment]
`type_metascript_result call_metascript(type_metascript_call_params params) {}`

**Comment by asmexcaliburwoods** [comment]
можно его указателем на функцию этого типа оформить.

**Comment by wipedlifepotato** [comment]
А чо через ptrace inject сразу, не?

**Comment by wipedlifepotato** [comment]
https://github.com/gaffe23/linux-inject

**Comment by asmexcaliburwoods** [comment]
хотя указатели на функции мешают aot оптимизациям, так что шустрее будет без указателя на функцию.

**Comment by wipedlifepotato** [comment]
metascript.c... типа любые языки подключать для модулей?  Но нужен основной

**Comment by wipedlifepotato** [comment]
Lua

**Comment by wipedlifepotato** [comment]
Lua
